### ISSUE TITLE
Warning message when running clinfo.

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/compute-runtime#384]
I've noticed when I type clinfo there was a warning say:

	NOTE:	your OpenCL library only supports OpenCL 2.2,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly

Should it be expected?

**Comment by JacekDanecki** [comment]
You need to update ocl-icd package to release 2.2.13, see: https://github.com/OCL-dev/ocl-icd/releases/tag/v2.2.13

**Comment by ArchangeGabriel** [comment]
I think their ocl-icd is up-to-date. The issue is rather that distro (like us, Arch Linux) build the Neo stack against system LLVM and don’t integrate the OpenCL 3.0 patches from here: https://github.com/intel/opencl-clang/blob/ocl-open-110/patches/clang/0001-OpenCL-3.0-support.patch. We (Arch) discussed integrating it, but it was decided too big to backport. So we will likely not have OpenCL 3.0 before LLVM 12.

**Comment by ArchangeGabriel** [comment]
Actually that does not seem quite exact: it was a bug in clinfo, which did not handle OpenCL 3.0. It has been fixed in a newer release, but I’m not sure whether OpenCL 3.0 really works without the aforementioned patch.

**Comment by JacekDanecki** [comment]
@CaoZhongZ Have you tried with newer ocl-icd?

**Comment by CaoZhongZ** [comment]
Problem still exists however does not affect other functionality. So I'm going to close it.
