### ISSUE TITLE
Packages are missing dependencies

### ISSUE THREAD

**Issue by eero-t** [intel/compute-runtime#470]
Debian/Ubuntu packaging files in the project have also another (admittedly minor) issue, besides claiming a dependency to a non-existing "intel-igc-opencl" package (issue #465).

They are missing dependency to the ICD loader package, "ocl-icd-libopencl1" for OpenCL and (I guess) "level-zero" for Level-Zero.

This dependency is in all the distro versions of e.g. "intel-opencl-icd" package:
* https://packages.debian.org/bullseye/intel-opencl-icd
* https://packages.debian.org/bookworm/intel-opencl-icd
* https://packages.debian.org/sid/intel-opencl-icd
* https://packages.ubuntu.com/focal/intel-opencl-icd
* https://packages.ubuntu.com/groovy/intel-opencl-icd
* https://packages.ubuntu.com/hirsute/intel-opencl-icd
* https://packages.ubuntu.com/impish/intel-opencl-icd
* source: https://salsa.debian.org/opencl-team/intel-compute-runtime/-/blob/master/debian/control

But missing from the packaging files in the "compute-runtime" project repo:
```
$ find -name control|xargs grep -A5 -e ^Package: -e ^Depends:
./scripts/packaging/opencl/ubuntu_20.04/control:Package: intel-opencl-icd
./scripts/packaging/opencl/ubuntu_20.04/control-Architecture: amd64 arm64
./scripts/packaging/opencl/ubuntu_20.04/control:Depends:
./scripts/packaging/opencl/ubuntu_20.04/control- ${shlibs:Depends},
./scripts/packaging/opencl/ubuntu_20.04/control- ${misc:Depends},
./scripts/packaging/opencl/ubuntu_20.04/control- intel-igc-opencl,
./scripts/packaging/opencl/ubuntu_20.04/control- intel-gmmlib
./scripts/packaging/opencl/ubuntu_20.04/control-Breaks:
--
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control:Package: intel-level-zero-gpu
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control-Architecture: amd64
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control:Depends:
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control- ${shlibs:Depends},
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control- ${misc:Depends},
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control- intel-igc-opencl,
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control- intel-gmmlib
./scripts/packaging/l0_gpu_driver/ubuntu_20.04/control-Description: Intel(R) Graphics Compute Runtime for oneAPI Level Zero
```
Note: most users do not notice this issue because they have installed some other package (e.g. "clinfo", or one of the OpenCL dev packages) which pulls in the ICD loader.

This issue is likely to be noticed only by people like me, who build containers which Docker file:
* is based on Ubuntu or Debian
* has separate build and runtime sections
* do not explicitly install indirect dependencies, as those should be pulled in by by (minimal) top level packages

And they start to use "compute-runtime" repository to get newer versions (in my case, to Intel internal repo).

But it's still an ugly packaging wart.  Packages should list as dependencies all the other packages that are needed for package to be usable [1], although in 99.9% of the cases user would happen to have them present on the system otherwise.

[1] Only exception for this in the packaging guidelines are dependencies on essential packages (ones that all installs will have).  Those should not be listed (to avoid package dependency resolving problems).

**Comment by JacekDanecki** [comment]
intel-igc-opencl package is provided in IGC releases: https://github.com/intel/intel-graphics-compiler/releases

ocl-icd-libopencl1 is not needed by Neo, this package is needed by applications which use Neo library. You can't link your application directly with Neo, you need to use libOpenCL library.

**Comment by eero-t** [comment]
> ocl-icd-libopencl1 is not needed by Neo, this package is needed by applications which use Neo library. You can't link your application directly with Neo, you need to use libOpenCL library.

Yes, that's what I'm doing.  And my point is that while the (simplified) example below works fine with Ubuntu 20.04:
```
FROM ubuntu:20.04 as build
RUN apt install build-essential ocl-icd-opencl-dev -y -q
COPY . .
RUN make cl-mem

FROM ubuntu:20.04
RUN apt install intel-opencl-icd -y -q
COPY --from=build cl-mem /usr/bin/
ENTRYPOINT cl-mem
``` 
It fails when Ubuntu 20.04 compute-runtime packages are upgraded to packages from this project (by adding their repo to APT).  This regression is because "intel-opencl-icd" has dropped the ICD loader dependency, although it's still an ICD "module" i.e. is useless without a loader.

As the deb format packaging policy says: https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps

> The Depends field should be used if the depended-on package is required for the depending package to provide a significant amount of functionality.


If in doubt, discuss with the distro maintainers how your dependencies should work, or just look how they do them:  https://salsa.debian.org/opencl-team/intel-compute-runtime/-/blob/master/debian/control

PS. I'm having this issue with the internal versions of the packages, but I'm filing the issue here as it concerns also the public version.

**Comment by eero-t** [comment]
Any progress in fixing this trivial issue (of the package not conforming to Debian/Ubuntu packaging policy and intel-opencl-icd upgrades failing in the indicated use-case)?

**Comment by JacekDanecki** [comment]
It's fixed with https://github.com/intel/compute-runtime/commit/543c854a3b7fc2590a0e0b72ad3260066ecfea89

**Comment by eero-t** [comment]
> It's fixed with [543c854](https://github.com/intel/compute-runtime/commit/543c854a3b7fc2590a0e0b72ad3260066ecfea89)

This fixes just the OpenCL dependency.  L0 backend package is still missing the dependency to L0 frontend, which is needed to actually use the backend.

PS does *L0* package actually need to depend on intel-igc-*opencl*?
