### ISSUE TITLE
[ARC A380/A750/A770) Please fix these problem (OpenCL) [Important!]

### ISSUE THREAD

**Issue by MisterHM80** [intel/compute-runtime#632]
It's about my OpenCL benchmark.

"Async Compute" test no longer works since driver version 4000. To 3975 went without problems.

With 4000 version, this only works if I reduce to 512, 512.

Equally buggy runs from the start with "HDR" and "TEXTURE"
If you run in order:
TEXTURE -> HDR -> TEXTURE -> HDR

Then we see the time indication for each 2nd run higher time.

With Nvidia or AMD there was no such behavior until now.

I would be very grateful if this could finally be fixed.
Even if priority is last with OpenCL.

Download (HardwareLuxx Forum)
https://www.hardwareluxx.de/community/threads/28-01-2023-r9-fury-added-amd-nvidia-intel-mrh-opencl-benchmark-rankliste.1302003/

Note : The same was already posted on Discord some time ago.

**Comment by JablonskiMateusz** [comment]
Hi @MisterHM80 
could you provide driver version reported by clinfo? I don't know how to map `driver version 4000` to our release

**Comment by MisterHM80** [comment]
Meant between 31.0.101.4032 and 31.0.101.4255 which doesn't work with Async Compute. 31.0.101.3975 or older works as it should.

Or have I misunderstood that?

**Comment by MisterHM80** [comment]
No. I don't see any point in it either.
The 5 other tests are running. Just not Async Compute since 4032 version.

Had just installed again 3975 and it works again.
I don't need to try anything.
Please try it to fix it.

**Comment by MisterHM80** [comment]
@JablonskiMateusz

Any news on this?

**Comment by Wagnard** [comment]
Hi, this is now fixed with Intel driver 31.0.101.4369

**Comment by MisterHM80** [comment]
Thank you for your feedback.
I'm glad that's fixed now with Async Compute :)

I hope, the HDR Bug will be fixed soon too
That make on 2nd Run slower (Bicubic, Texture and Async Compute), if before run first time HDR.
Same for HDR after 2nd Run.

**Comment by MisterHM80** [comment]
@JablonskiMateusz
What about the HDR bug now? Still exists until now.
Start the Tool and 1.st run with HDR. 2.nd run is up to 33% slower.

**Comment by MisterHM** [comment]
B580 dont have HDR Bug like A770.
But i am not happy about Async Compute Performance on both.
Why so slow?

**Comment by MisterHM80** [comment]
B580 dont have HDR Bug like A770.
But i am not happy about Async Compute Performance on both.
Why so slow?

**Comment by MisterHM80** [comment]
Is there any known issue with the B580 when displaying GridView? I'm currently expanding the new mode—including GridView—for an upcoming version. With the B580, the more runs are executed, the longer it takes to add new entries. In contrast, the A770 and the 285K’s iGPU complete their entries instantly after each run.

Best regards

**Comment by MisterHM80** [comment]
Any ETA when this fix will reach public Arc B‑Series drivers?

**Comment by jwarchul** [comment]
Hi @MisterHM80,

We sincerely apologize for the delayed response.

* **HDR Bug:** The fix for this issue is already available in the [latest driver version - `32.0.101.8974`](https://www.intel.com/content/www/us/en/download/785597/intel-arc-graphics-windows.html). Could you please confirm it?

* **Async Compute Performance:** The issue has been identified and the fix has already been merged. It should be included in the next driver release. We will update you here as soon as it becomes available.

* **GridView Issue:** Could you please provide more details regarding this problem, along with the steps to reproduce it?

Thank you for your valuable contribution, and apologies once again for the long wait.

**Comment by MisterHM80** [comment]
@jwarchul 

HDR:  
On the A770/iGPU (A‑Series, 285K), the previous slowdown after the second run no longer occurs once the tool has been opened. The HDR behavior is now stable on the A‑Series.

GridView:  That is how it appears in the video during the recording (Screen Recorder 4).
I created a video demonstrating the different behavior between the iGPU (A‑Series) and the ARC PRO B70 (B‑Series). You can clearly see that focus switching between my MrH OpenCL Benchmark and the Windows timer works smoothly on the A‑Series, while the B‑Series shows visible slowdowns: when the benchmark window has focus, the Windows timer increments much more slowly and the system responds sluggishly; when the timer window has focus, the B‑Series behaves normally.
https://www.youtube.com/watch?v=QlFW5t4FI4I

Edit: Here without recording.
For 4 WU + 10 RUN
[iGPU need 7min 17,89sec](https://s1.directupload.eu/images/user/260818/ew7jlc75.png) <- A770 same.
[ARC PRO B70 need 10min 1,93sec](https://s1.directupload.eu/images/user/260818/r66i9lwg.png)

**Comment by MisterHM80** [comment]
@jwarchul 

Was the significant Texture performance improvement in driver 32.0.101.8974 (ARC A770) intentional?
(8864 → 8974: Texture Extreme 103 ms → 42 ms)

**Comment by jwarchul** [comment]
Hi @MisterHM80,

Thank you for the additional information. We will continue investigating this issue internally and will update you as soon as we have any findings.

Thanks for your cooperation.
