### ISSUE TITLE
Malformed L0 driver version string from github release packages

### ISSUE THREAD

**Issue by ph0b** [intel/compute-runtime#826]
This issue got discovered and root caused initially from Blender: https://projects.blender.org/blender/blender/issues/137277

When using .deb packages from github releases, such as https://github.com/intel/compute-runtime/releases/tag/25.09.32961.5, zeIntelGetDriverVersionString which is supposed to report the driver version in the form: `Major.Minor.Patch+Optional` as defined in https://github.com/intel/compute-runtime/blob/master/level_zero/doc/experimental_extensions/GET_DRIVER_VERSION_STRING.md, doesn't. 

Instead of `1.6.32961+5` for this recent release, it returns `1.6.32961.500000`.
This issue is present since at least https://github.com/intel/compute-runtime/releases/tag/24.39.31294.12

Since `std::to_string(32961.5)` is `32961.500000`, my analysis is that instead of being built with `NEO_VERSION_BUILD=32961` and `NEO_VERSION_HOTFIX=5`, the packages are built with `NEO_VERSION_BUILD=32961.5` and `NEO_VERSION_HOTFIX=0`.

**Comment by nsirgien** [comment]
Fixed in https://github.com/intel/compute-runtime/commit/fba685008bf528b56dee5319782cdb11eb1ac75c, as far as I know.

**Comment by eero-t** [comment]
@ph0b Can you verify whether this is fixed now?

**Comment by ph0b** [comment]
At the moment, the mentioned fix isn't part of any release branch nor release packages.
I can manually verify with for example `sycl-ls` once release packages with a fix are made available but it'd be best if a unit test could be added as well.

**Comment by JablonskiMateusz** [comment]
@ph0b  fix is available in https://github.com/intel/compute-runtime/releases/tag/25.27.34303.5

**Comment by JablonskiMateusz** [comment]
@ph0b  could you confirm the latest release works fine?

**Comment by ph0b** [comment]
@JablonskiMateusz I've tried latest release https://github.com/intel/compute-runtime/releases/tag/25.31.34666.3 on WSL Ubuntu 24.04, I still get the malformed version string when running `sycl-ls`, ie. `1.6.34666.300000` instead of `1.6.34666+3`:

```
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0xe20b] 20.1.0 [1.6.34666.300000]
[level_zero:gpu][level_zero:1] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0xa780] 12.2.0 [1.6.34666.300000]
```

Digging a bit deeper, it appears that previous fix is removed from release branches, see https://github.com/intel/compute-runtime/blob/25.31.34666.3/version.cmake doesn't contain
```
if(NEO_VERSION_BUILD MATCHES "^([0-9]+)\\.([0-9]+)$")
  set(NEO_VERSION_BUILD "${CMAKE_MATCH_1}")
  set(NEO_VERSION_HOTFIX "${CMAKE_MATCH_2}")
endif()
```

**Comment by JablonskiMateusz** [comment]
@ph0b  thanks for catching that

**Comment by ph0b** [comment]
Packages from Fedora are also impacted: https://bugzilla.redhat.com/show_bug.cgi?id=2392875 / https://projects.blender.org/blender/blender/issues/145449

**Comment by JablonskiMateusz** [comment]
@ph0b  change is re-applied to release 25.35 branch, should be available in the next release https://github.com/intel/compute-runtime/commit/68d43aafe612c7409d9e9984a658d88d527ce8dc

**Comment by kgibala** [comment]
@ph0b can you confirm that this issue could be closed, thanks.

**Comment by ph0b** [comment]
@kgibala it can be closed only once a release package with the fixes will have been published. This is not the case yet.

**Comment by ph0b** [comment]
I can confirm the issue is fixed with today's release [25.35.35096.9](https://github.com/intel/compute-runtime/releases/tag/25.35.35096.9), thank you!
```
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0xe20b] 20.1.0 [1.6.35096+9]
[level_zero:gpu][level_zero:1] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Graphics [0xa780] 12.2.0 [1.6.35096+9]
```
